FROM n8nio/n8n:latest
USER root
RUN mkdir -p /home/node/.n8n && chown -R 1000:1000 /home/node/.n8n
USER 1000
ENV N8N_PORT=10000
ENV N8N_METRICS=false
ENV DB_TYPE=sqlite
ENV EXECUTIONS_DATA_SAVE_ON_ERROR=all
ENV EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
ENV EXECUTIONS_DATA_PRUNE=true
ENV EXECUTIONS_DATA_MAX_AGE=24
EXPOSE 10000
CMD ["n8n", "start"]
